"""add crls table

Revision ID: 1afa5b58e9d0
Revises: 80c6e9f72e95
Create Date: 2020-01-12 12:26:10.377655

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1afa5b58e9d0' # pragma: allowlist secret
down_revision = '80c6e9f72e95' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crls',
        sa.Column('serial_no', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('serial_no'),
        sa.UniqueConstraint('serial_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crls')
    # ### end Alembic commands ###
