"""add users.cert_serial

Revision ID: 80c6e9f72e95
Revises: 5d7198d34b91
Create Date: 2020-01-10 06:24:02.584517

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '80c6e9f72e95' # pragma: allowlist secret
down_revision = '5d7198d34b91' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cert_serial', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cert_serial')
    # ### end Alembic commands ###
